### ISSUE TITLE
Does not load after 1.0.3 update.

### ISSUE THREAD

**Issue by HyperRamzey** [InfernoDragon0/CotLMods#1]
[LogOutput.log](https://github.com/InfernoDragon0/CotLMods/files/9668916/LogOutput.log)

**Comment by InfernoDragon0** [comment]
May i know which version of the game you tested on? I have tested on v1.0.16 hotfix and it seems to be working fine for me

Tested on:
- v1.0.16 + Hotfix CotL
- BepInEx 5.4.19
- COTL_API 0.1.4
- CotLChef 1.0.3

**Comment by InfernoDragon0** [comment]
I found the issue, will be fixed in the next update. Thanks for reporting!
