### ISSUE TITLE
1.1.6 Fishing Hut

### ISSUE THREAD

**Issue by Khutlas** [InfernoDragon0/CotLMods#10]
Had some issues when demolishing down buildings where if i attempted to do so it will freeze the game and give me no choice but to force close it.

most commonly the fishing hut.

**Comment by InfernoDragon0** [comment]
Hi, are you able to provide any logs when this happened? you can get the log file from Bepinex > Logoutput.log.

Thank you for the report!

**Comment by Khutlas** [comment]
Sozzles for the late reply. Dunno really, did look in the logs but it didn't say much to well have information plus because it completely stops the logs after freezing so that's the most confusing part
all I know, after construction of the fishing hut. I am unable to move nor demolish the building and causes the game to either freeze or crash.

If I get the chance I'll attempt to get the logs and send it to ya, cheers.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by InfernoDragon0** [comment]
Closed as this should resolve itself with the latest COTL API and CotlMiniMods build
