### ISSUE TITLE
[BUG] The menu that opens on the left broke

### ISSUE THREAD

**Issue by Nick56731** [InfernoDragon0/CotLMods#12]
The menu that appears when you need to select a follower (ex. revive, sacrifice) broke and can not be interacted with and wont even show. You will be stuck in the menu until you press ESC, then the menu will show for a second but you cant interact with it and the ritual will be cancelled. This also applies to mind reading

I also found this big red bunch in the Console so i will post it here

[Error  : Unity Log] InvalidOperationException: Collection was modified; enumeration operation may not execute.
Stack trace:
System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () (at <75633565436c42f0a6426b33f0132ade>:0)
System.Collections.Generic.List`1+Enumerator[T].MoveNext () (at <75633565436c42f0a6426b33f0132ade>:0)
Interaction_TempleAltar+<FollowersEnterForSermonRoutine>d__69.MoveNext () (at <7a81166dc9784f14af5f198d0b134f87>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <008a787f2823430aae87e927a51ccf8d>:0)

**Comment by InfernoDragon0** [comment]
Hi there, thanks for the report. By any chance you are also running with the mod nofollowerlevellimit? If so, try running without it and see if it happens again.

**Comment by Nick56731** [comment]
I did have the nofollowerlevellimit mod and after reporting another bug there it seems to have fixed itself

**Comment by InfernoDragon0** [comment]
good to hear!
